### ISSUE TITLE
Handling multiple meanings for a term

### ISSUE THREAD

**Issue by imantsm** [AberystwythSystemsBiology/MEDIALpy#1]
Hi! This looks like a cool tool that you've built out of the glossary that I've been working on.

I haven't run your code yet, but just taking a glance at the code, I'm not sure the code handles multiple meanings for one term. For example, I think I have something like 6 or 7 meanings for 'ACS'. Maybe if you made your 'meaning' variable an array of strings instead of a string? Again, I haven't run your code yet, so I may have mis-read it. 

Cheers, and good job!

**Comment by KeironO** [comment]
No need to worry:

```python
>>> import medialpy
>>> term = medialpy.find("ACS")
>>> term.meaning
['American Cancer Society', 'NYC Administration for Children’s Services', 'Abdominal Compartment Syndrome', 'acute compartment syndrome', 'acute coronary syndrome', 'American College of Surgeons', 'abnormally contracting segments']
```
